### ISSUE TITLE
Feature: Specify subset of permissions to grant to the token

### ISSUE THREAD

**Issue by bradynpoulsen** [getsentry/action-github-app-token#65]
## Overview

Inspired by `tibdex/github-app-token`, I propose that a `permissions` input is added to be able to configure a desired subset of permissions that should be issued to the token.

## Example Usage

```yaml
- uses: getsentry/action-github-app-token@v2
  with:
    app_id: ${{ secrets.APP_ID }}
    private_key: ${{ secrets.APP_PRIVATE_KEY }}
    permissions: |
      {"contents": "read"}
```

## Implementation

Per [octokit/auth-app.js](https://github.com/octokit/auth-app.js/blob/main/src/types.ts#L45), it appears that a permissions argument can be specified to the `appOctokit.auth` call. I believe having a `permissions` input that is a JSON map of desired permissions would be the easiest adoption of this function.
